# -*- coding: utf-8 -*-
"""Install / uninstall the Russian localisation.

Files that the 1.50 patch can redirect from a mod config are left in
150/mods/rus/lbx and referenced from RUS.CFG, so no game file is touched.
The handful of LBX files the patch has no config parameter for are copied over
the originals in the game root; the originals go to backup/root first.
"""
import sys, os, shutil, glob
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from paths import PROJ, ROOT
MOD = os.path.join(ROOT, '150', 'mods', 'rus')
MODLBX = os.path.join(MOD, 'lbx')
BACKUP = os.path.join(PROJ, 'backup', 'root')

# lbx name -> config parameter provided by the 1.50 patch
PARAM = {
    'CREDITS.LBX': 'credits.lbx', 'DIPLOMSE.LBX': 'diplomse.lbx',
    'ESTRINGS.LBX': 'estrings.lbx', 'EVENTMSE.LBX': 'eventmse.lbx',
    'FONTS.LBX': 'fonts.lbx', 'HELP.LBX': 'help.lbx',
    'HERODATA.LBX': 'herodata.lbx', 'HESTRNGS.LBX': 'hestrngs.lbx',
    'KENTEXT.LBX': 'kentext.lbx', 'KENTEXT1.LBX': 'kentext1.lbx',
    'MAINTEXT.LBX': 'maintext.lbx', 'RACENAME.LBX': 'racename.lbx',
    'RSTRING0.LBX': 'rstring0.lbx', 'SHIPNAME.LBX': 'shipname.lbx',
    'SKILDESC.LBX': 'skildesc.lbx', 'STARNAME.LBX': 'starname.lbx',
    'TECHDESC.LBX': 'techdesc.lbx', 'TECHNAME.LBX': 'techname.lbx',
}
# no config parameter exists -> the file in the game root has to be replaced
ROOT_REPLACE = ['IFONTS.LBX', 'MSGENG.LBX', 'ENGMSG.LBX', 'JIMTEXT.LBX', 'JIMTEXT2.LBX',
                'BILLTEXT.LBX', 'BILLTEX2.LBX', 'COUNCMSG.LBX', 'ANTARMSG.LBX',
                'RACESTUF.LBX', 'PLAYSPEC.LBX', 'CUSTMSTR.LBX']

# mod_name / mod_desc are for the Launcher only (the game prints its own
# label, see cfg/EXTRA.CFG).  The Launcher reads config files as raw bytes and
# never decodes these two values - a checkbox label or the hover text shows
# CP1251 and UTF-8 alike as Latin-1 mojibake - so they have to be plain ASCII.
HEADER = """# ================================================ #
# --      MOO2 1.50 - Russian localisation      -- #
# ================================================ #
#
# Generated by tools/install.py - edit that script, not this file.

  mod_name  = "Russian";
  mod_id    = RUS;
  mod_class = lang;
  mod_order = 900;
  mod_desc  = "Russian translation: text, fonts and patch strings (1.50.26).";

"""
EXTRA_SRC = os.path.join(PROJ, 'cfg', 'EXTRA.CFG')


def gen_cfg():
    lines = [HEADER]
    for name in sorted(PARAM):
        if os.path.exists(os.path.join(MODLBX, name)):
            lines.append('  %-13s = lbx\\%s;\n' % (PARAM[name], name))
    # in-game strings: CP1251, one folder down so the Launcher does not take
    # the file for a mod (it scans 150/mods/*/*.CFG)
    os.makedirs(os.path.join(MOD, 'cfg'), exist_ok=True)
    extra = open(EXTRA_SRC, encoding='utf-8').read().encode('cp1251')
    with open(os.path.join(MOD, 'cfg', 'EXTRA.CFG'), 'wb') as f:
        f.write(extra)
    stale = os.path.join(MOD, 'EXTRA.CFG')
    if os.path.exists(stale):
        os.remove(stale)
    lines.append('\n  include cfg\\EXTRA.CFG;\n')
    lines.append('\n# END\n')
    data = ''.join(lines).encode('ascii')
    with open(os.path.join(MOD, 'RUS.CFG'), 'wb') as f:
        f.write(data)
    return len(data)


def enable(on=True):
    p = os.path.join(ROOT, '150', 'ENABLE.CFG')
    txt = open(p, 'rb').read()
    has = b'enable RUS;' in txt
    if on and not has:
        open(p, 'wb').write(txt.rstrip() + b'\nenable RUS;\n')
    elif not on and has:
        open(p, 'wb').write(txt.replace(b'enable RUS;\n', b'').replace(b'enable RUS;', b''))
    # make it survive a Launcher regeneration of ENABLE.CFG
    p2 = os.path.join(ROOT, 'ORION2.CFG')
    txt2 = open(p2, 'rb').read()
    marker = b'\n  enable RUS;   # Russian localisation\n'
    if on and marker not in txt2:
        anchor = b'  enable USER;'
        if anchor in txt2:
            txt2 = txt2.replace(anchor, marker.strip(b'\n').rstrip() + b'\n' + anchor, 1)
        else:
            txt2 = txt2 + marker
        if not os.path.exists(os.path.join(BACKUP, 'ORION2.CFG')):
            os.makedirs(BACKUP, exist_ok=True)
            shutil.copyfile(p2, os.path.join(BACKUP, 'ORION2.CFG'))
        open(p2, 'wb').write(txt2)
    elif not on and marker.strip(b'\n') in txt2:
        open(p2, 'wb').write(txt2.replace(marker.strip(b'\n') + b'\n', b''))


def install():
    os.makedirs(BACKUP, exist_ok=True)
    n = 0
    for name in ROOT_REPLACE:
        src = os.path.join(MODLBX, name)
        if not os.path.exists(src):
            continue
        dst = os.path.join(ROOT, name)
        bak = os.path.join(BACKUP, name)
        if not os.path.exists(bak):
            shutil.copyfile(dst, bak)
        shutil.copyfile(src, dst)
        n += 1
        print('  root <- %s' % name)
    size = gen_cfg()
    note = os.path.join(MOD, 'README.TXT')     # left behind by uninstall
    if os.path.exists(note):
        os.remove(note)
    enable(True)
    print('RUS.CFG written (%d bytes), %d root files replaced, mod enabled.' % (size, n))


LEFTOVER_NOTE = """Master of Orion II - Russian translation (moo2-rus), uninstalled.

The files in lbx\\ are the ORIGINAL English ones.  They stay because a saved
game remembers the exact LBX paths of the mods it was started with (for
example \\150\\mods\\RUS\\lbx\\HELP.LBX) and the game refuses to load the save
if one of them is missing.  With these copies such saves open in English.
It is safe to delete this folder once you no longer need those saves.

Перевод удалён. В lbx\\ лежат ОРИГИНАЛЬНЫЕ английские файлы: сохранения,
начатые с переводом, помнят пути к файлам мода и без них не загружаются.
С этими копиями такие сохранения открываются на английском. Папку можно
удалить, когда эти сохранения больше не нужны.
"""


def uninstall():
    n = 0
    for name in ROOT_REPLACE:
        bak = os.path.join(BACKUP, name)
        if os.path.exists(bak):
            shutil.copyfile(bak, os.path.join(ROOT, name))
            n += 1
    enable(False)
    # A save stores the resolved LBX paths of its config, so games started
    # with the translation look for \150\mods\RUS\lbx\*.LBX when loaded and the
    # game terminates if one is missing ("... could not be found").  Keep the
    # folder, but put the original English files in it: those saves then load
    # in English, consistent with the restored EXE.  RUS.CFG goes, so the
    # Launcher no longer lists the mod.
    import dump_all
    kept = 0
    for name in PARAM:
        dst = os.path.join(MODLBX, name)
        if os.path.exists(dst):
            src = dump_all.source_for(name)
            if src and os.path.abspath(src) != os.path.abspath(dst):
                shutil.copyfile(src, dst)
                kept += 1
    for name in ROOT_REPLACE:
        p = os.path.join(MODLBX, name)
        if os.path.exists(p):
            os.remove(p)
    for p in (os.path.join(MOD, 'RUS.CFG'), os.path.join(MOD, 'cfg', 'EXTRA.CFG')):
        if os.path.exists(p):
            os.remove(p)
    if os.path.isdir(os.path.join(MOD, 'cfg')) and not os.listdir(os.path.join(MOD, 'cfg')):
        os.rmdir(os.path.join(MOD, 'cfg'))
    if os.path.isdir(MODLBX):
        with open(os.path.join(MOD, 'README.TXT'), 'w', encoding='utf-8') as f:
            f.write(LEFTOVER_NOTE)
    print('restored %d root files, mod disabled; %d original LBX left in 150/mods/rus/lbx '
          'for saves started with the translation.' % (n, kept))


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'uninstall':
        uninstall()
    else:
        install()
