# -*- coding: utf-8 -*-
"""Russian spellings for the words MOO2 builds its default ship names from.

These are names, not descriptions, so they are transcribed rather than
translated: a ship called Sparrow is Спэрроу the same way a carrier called
Enterprise is Энтерпрайз.  Transcription also keeps two word names working -
there is no adjective to agree with anything.
"""
WORDS = {
    'Anaconda': 'Анаконда', 'Annihilator': 'Аннигилятор',
    'Armageddon': 'Армагеддон', 'Asteriod': 'Астероид', 'Aurora': 'Аврора',
    'Avenger': 'Эвенджер', 'Backsword': 'Бэксворд', 'Badger': 'Бэджер',
    'Balista': 'Баллиста', 'Barracuda': 'Барракуда', 'Bear': 'Бэр',
    'Biter': 'Байтер', 'Blackhawk': 'Блэкхок', 'Blade': 'Блейд',
    'Bloodfoot': 'Бладфут', 'Blue': 'Блю', 'Boa': 'Боа', 'Bobcat': 'Бобкэт',
    'Bola': 'Бола', 'Bow': 'Боу', 'Buzzard': 'Баззард',
    'Cannonade': 'Канонада', 'Carraca': 'Каррака', 'Catapult': 'Катапульта',
    'Cave': 'Кейв', 'Chaser': 'Чейзер', 'Cheetah': 'Чита',
    'Cinqueda': 'Чинкуэда', 'Claymore': 'Клеймор', 'Cobra': 'Кобра',
    'Comet': 'Комета', 'Condor': 'Кондор', 'Corona': 'Корона',
    'Corsair': 'Корсар', 'Corvette': 'Корвет', 'Courageous': 'Кариджес',
    'Courier': 'Курьер', 'Coyote': 'Койот', 'Crusader': 'Крусейдер',
    'Cub': 'Каб', 'Cutlass': 'Катласс', 'Dagger': 'Дэггер', 'Dark': 'Дарк',
    'Dbuh': 'Дбух', 'Defiler': 'Дефайлер', 'Demon': 'Демон',
    'Destructor': 'Деструктор', 'Devastator': 'Девастатор', 'Dingo': 'Динго',
    'Dirk': 'Дирк', 'Dragon': 'Дракон', 'Draken': 'Дракен',
    'Dreadnought': 'Дредноут', 'Dreadwing': 'Дредвинг', 'Eagle': 'Игл',
    'Escort': 'Эскорт', 'Etendard': 'Этандар', 'Excaliber': 'Экскалибур',
    'Falcata': 'Фальката', 'Falchard': 'Фальшион', 'Falcon': 'Фалькон',
    'Fang': 'Фэнг', 'Feather': 'Фезер', 'Ferret': 'Феррет',
    'Fighter': 'Файтер', 'Fire': 'Файр', 'Fisher': 'Фишер', 'Flail': 'Флейл',
    'Foe': 'Фо', 'Fury': 'Фьюри', 'Gatherer': 'Гэзерер', 'Gauche': 'Гош',
    'Gila': 'Хила', 'Gladius': 'Гладиус', 'Gnome': 'Гном', 'Goblin': 'Гоблин',
    'Goshawk': 'Гошок', 'Gremlin': 'Гремлин', 'Griffin': 'Гриффин',
    'Gripen': 'Грипен', 'Grison': 'Гризон', 'Grizzly': 'Гризли',
    'Guardian': 'Гардиан', 'Halberd': 'Алебарда', 'Hammer': 'Хаммер',
    'Harbinger': 'Харбинджер', 'Harrier': 'Харриер',
    'Hatsutaka': 'Хацутака', 'Hawk': 'Хок', 'Hellcat': 'Хеллкэт',
    'Helldiver': 'Хеллдайвер', 'Hornet': 'Хорнет', 'Hunter': 'Хантер',
    'Iguana': 'Игуана', 'Infidel': 'Инфидел', 'Intangible': 'Интэнджибл',
    'Interceptor': 'Интерцептор', 'Interdictor': 'Интердиктор',
    'Intruder': 'Интрудер', 'Invincible': 'Инвинсибл', 'Jaguar': 'Ягуар',
    'Jay': 'Джей', 'Karabela': 'Карабела', 'Katana': 'Катана',
    'Katar': 'Катар', 'Kestrel': 'Кестрел', 'King': 'Кинг', 'Knight': 'Найт',
    'Kodiak': 'Кадьяк', 'Kris': 'Крис', 'Lark': 'Ларк',
    'Lightning': 'Лайтнинг', 'Locaber': 'Локабер', 'Lynx': 'Линкс',
    'Mace': 'Мейс', 'Main': 'Мэн', 'Malvosin': 'Мальвуазен', 'Mamba': 'Мамба',
    'Manta': 'Манта', 'Marauder': 'Мародёр', 'Menace': 'Менас',
    'Messenger': 'Мессенджер', 'Meteor': 'Метеор', 'Mink': 'Минк',
    'Minotaur': 'Минотавр', 'Mirage': 'Мираж', 'Morey': 'Мурена',
    'Mustang': 'Мустанг', 'Nemesis': 'Немезида', 'Nexus': 'Нексус',
    'Nova': 'Нова', 'Nymph': 'Нимфа', 'Oasis': 'Оазис', 'Ogre': 'Огр',
    'Omnipotent': 'Омнипотент', 'Overseer': 'Оверсир', 'Paladin': 'Паладин',
    'Panda': 'Панда', 'Panther': 'Пантера', 'Patrol': 'Патруль',
    'Pegasus': 'Пегас', 'Phantom': 'Фантом', 'Phoenix': 'Феникс',
    'Pike': 'Пайк', 'Pikemaul': 'Пайкмол', 'Pin': 'Пин', 'Piranha': 'Пиранья',
    'Polecat': 'Полкэт', 'Prophet': 'Профет', 'Punisher': 'Панишер',
    'Python': 'Питон', 'Quetzicoatl': 'Кецалькоатль', 'Rafale': 'Рафаль',
    'Raider': 'Рейдер', 'Rapier': 'Рапира', 'Ravager': 'Равейджер',
    'Red': 'Ред', 'Relentless': 'Релентлесс', 'Render': 'Рендер',
    'Rhino': 'Рино', 'Roc': 'Рок', 'Sabre': 'Сабля',
    'Sabretooth': 'Сейбртус', 'Sage': 'Сейдж', 'Scimitar': 'Ятаган',
    'Scorpion': 'Скорпион', 'Seeker': 'Сикер', 'Seibe': 'Сейбе',
    'Seraphin': 'Серафим', 'Shark': 'Шарк', 'Sharpbeak': 'Шарпбик',
    'Ship': 'Шип', 'Shurikin': 'Сюрикен', 'Skein': 'Скейн', 'Skink': 'Скинк',
    'Skua': 'Скуа', 'Skyhawk': 'Скайхок', 'Skyquake': 'Скайквейк',
    'Soarer': 'Сорер', 'Sparrow': 'Спэрроу', 'Spider': 'Спайдер',
    'Spitfire': 'Спитфайр', 'Sprite': 'Спрайт', 'Star': 'Стар',
    'Starling': 'Старлинг', 'Stiletto': 'Стилет', 'Stingray': 'Стингрей',
    'Stoat': 'Стоат', 'Streak': 'Стрик', 'Striker': 'Страйкер', 'Sun': 'Сан',
    'Swiftpaw': 'Свифтпо', 'Swiftwing': 'Свифтвинг', 'Tachi': 'Тати',
    'Tarantula': 'Тарантул', 'Thrush': 'Траш', 'Thunder': 'Тандер',
    'Thunderbolt': 'Тандерболт', 'Tooth': 'Тус', 'Tormentor': 'Торментор',
    'Tornado': 'Торнадо', 'Trebuchet': 'Требушет', 'Troll': 'Тролль',
    'Tyrant': 'Тирант', 'Ursus': 'Урсус', 'Venom': 'Веном',
    'Violator': 'Вайолейтор', 'Viper': 'Вайпер', 'War': 'Уор',
    'Warbear': 'Уорбэр', 'Warcat': 'Уоркэт', 'Wasp': 'Уосп',
    'Widow': 'Уидоу', 'Wildcat': 'Уайлдкэт', 'Wing': 'Уинг', 'Wolf': 'Вульф',
    'Wolverine': 'Росомаха', 'Wyvern': 'Виверна', 'Claw': 'Клоу',
}
